spring.application.name=IT211_project

# MYSQL DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/it211_project_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT CONFIG
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# REDIS CONFIG
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Disable H2
spring.h2.console.enabled=false

# Fix Swagger path pattern
spring.mvc.pathmatch.matching-strategy=ant_path_matcher